-- Run this migration in Supabase SQL Editor after database.sql / ADMIN_SETUP.sql.
alter table public.providers add column if not exists project_videos jsonb not null default '[]'::jsonb;
create table if not exists public.site_banners (
  id bigint generated by default as identity primary key,
  title text not null, description text not null default '', image text not null default '',
  video text not null default '', link text not null default '', active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.site_products (
  id bigint generated by default as identity primary key,
  name text not null, description text not null default '', category text not null default '',
  price text not null default '', contact text not null default '', image text not null default '',
  video text not null default '', link text not null default '', active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.site_banners enable row level security;
alter table public.site_products enable row level security;
drop policy if exists "Public can read active banners" on public.site_banners;
create policy "Public can read active banners" on public.site_banners for select using (active = true);
drop policy if exists "Admins manage banners" on public.site_banners;
create policy "Admins manage banners" on public.site_banners for all to authenticated using (exists (select 1 from public.user_roles r where r.user_id = auth.uid() and r.role in ('admin','moderator'))) with check (exists (select 1 from public.user_roles r where r.user_id = auth.uid() and r.role in ('admin','moderator')));
drop policy if exists "Public can read active products" on public.site_products;
create policy "Public can read active products" on public.site_products for select using (active = true);
drop policy if exists "Admins manage products" on public.site_products;
create policy "Admins manage products" on public.site_products for all to authenticated using (exists (select 1 from public.user_roles r where r.user_id = auth.uid() and r.role in ('admin','moderator'))) with check (exists (select 1 from public.user_roles r where r.user_id = auth.uid() and r.role in ('admin','moderator')));
