-- Classic Events Connect — COMPLETE SUPABASE PRODUCTION SCHEMA
-- Safe to run in a fresh Supabase project. Re-running is designed to be idempotent.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default 'Member',
  contact text,
  type text,
  about text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.providers (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.profiles(id) on delete cascade,
  name text not null,
  type text not null,
  photo text,
  location text,
  price text,
  contact text,
  description text,
  projects jsonb not null default '[]'::jsonb,
  project_images jsonb not null default '[]'::jsonb,
  status text not null default 'pending' check (status in ('pending','approved','rejected','suspended')),
  verified boolean not null default false,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_media (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.providers(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  title text,
  description text,
  image_url text not null,
  storage_path text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.profiles(id) on delete cascade,
  name text not null,
  date date,
  time text,
  city text,
  type text,
  fee text,
  target text,
  description text,
  cover_image text,
  status text not null default 'pending' check (status in ('pending','approved','rejected','cancelled','completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.profiles(id) on delete set null,
  provider_id bigint references public.providers(id) on delete set null,
  provider_name text,
  provider_type text,
  customer text,
  contact text,
  event text,
  date date,
  time text,
  location text,
  budget text,
  message text,
  status text not null default 'pending' check (status in ('pending','accepted','rejected','cancelled','completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  reviewer_id uuid references public.profiles(id) on delete set null,
  provider_id bigint references public.providers(id) on delete set null,
  provider_name text not null,
  rating integer not null check (rating between 1 and 5),
  text text,
  status text not null default 'published' check (status in ('pending','published','hidden','removed')),
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) on delete set null,
  receiver_id uuid references public.profiles(id) on delete set null,
  booking_id bigint references public.bookings(id) on delete set null,
  text text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  text text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin','moderator')),
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists providers_status_idx on public.providers(status);
create index if not exists providers_owner_idx on public.providers(owner_id);
create index if not exists providers_type_idx on public.providers(type);
create index if not exists providers_featured_idx on public.providers(featured);
create index if not exists project_media_provider_idx on public.project_media(provider_id);
create index if not exists events_status_date_idx on public.events(status,date);
create index if not exists bookings_customer_idx on public.bookings(customer_id);
create index if not exists bookings_provider_idx on public.bookings(provider_id);
create index if not exists bookings_status_idx on public.bookings(status);
create index if not exists reviews_provider_idx on public.reviews(provider_id);
create index if not exists messages_receiver_idx on public.messages(receiver_id,read);
create index if not exists notifications_user_idx on public.notifications(user_id,read);
create index if not exists audit_actor_idx on public.audit_log(actor_id,created_at desc);

-- Updated-at helper.
create or replace function public.set_updated_at()
returns trigger language plpgsql security invoker as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists providers_updated_at on public.providers;
create trigger providers_updated_at before update on public.providers for each row execute function public.set_updated_at();
drop trigger if exists events_updated_at on public.events;
create trigger events_updated_at before update on public.events for each row execute function public.set_updated_at();
drop trigger if exists bookings_updated_at on public.bookings;
create trigger bookings_updated_at before update on public.bookings for each row execute function public.set_updated_at();

-- Automatically create a profile when a new Auth user signs up.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id,name,contact,type)
  values (new.id, coalesce(new.raw_user_meta_data->>'name','Member'), new.email, coalesce(new.raw_user_meta_data->>'type','Customer'))
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_admin_or_moderator()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.user_roles where user_id=auth.uid() and role in ('admin','moderator')); $$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.user_roles where user_id=auth.uid() and role='admin'); $$;

-- RLS.
alter table public.profiles enable row level security;
alter table public.providers enable row level security;
alter table public.project_media enable row level security;
alter table public.events enable row level security;
alter table public.bookings enable row level security;
alter table public.reviews enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;
alter table public.user_roles enable row level security;
alter table public.site_settings enable row level security;
alter table public.audit_log enable row level security;

-- Drop/recreate policies so the script can be safely rerun.
do $$ declare r record; begin
  for r in select schemaname,tablename,policyname from pg_policies where schemaname='public' and tablename in ('profiles','providers','project_media','events','bookings','reviews','messages','notifications','user_roles','site_settings','audit_log') loop
    execute format('drop policy if exists %I on %I.%I',r.policyname,r.schemaname,r.tablename);
  end loop;
end $$;

create policy profiles_select on public.profiles for select using (true);
create policy profiles_insert_own on public.profiles for insert with check (auth.uid()=id);
create policy profiles_update_own on public.profiles for update using (auth.uid()=id or public.is_admin()) with check (auth.uid()=id or public.is_admin());

create policy providers_public_read on public.providers for select using (status='approved' or owner_id=auth.uid() or public.is_admin_or_moderator());
create policy providers_insert_own on public.providers for insert with check (auth.uid()=owner_id);
create policy providers_update_owner_or_admin on public.providers for update using (owner_id=auth.uid() or public.is_admin_or_moderator()) with check (owner_id=auth.uid() or public.is_admin_or_moderator());
create policy providers_delete_admin on public.providers for delete using (public.is_admin());

create policy project_media_public_read on public.project_media for select using (exists(select 1 from public.providers p where p.id=provider_id and (p.status='approved' or p.owner_id=auth.uid())) or public.is_admin_or_moderator());
create policy project_media_insert_owner on public.project_media for insert with check (owner_id=auth.uid() or public.is_admin_or_moderator());
create policy project_media_update_owner_admin on public.project_media for update using (owner_id=auth.uid() or public.is_admin_or_moderator()) with check (owner_id=auth.uid() or public.is_admin_or_moderator());
create policy project_media_delete_owner_admin on public.project_media for delete using (owner_id=auth.uid() or public.is_admin_or_moderator());

create policy events_public_read on public.events for select using (status='approved' or owner_id=auth.uid() or public.is_admin_or_moderator());
create policy events_insert_own on public.events for insert with check (auth.uid()=owner_id);
create policy events_update_owner_admin on public.events for update using (owner_id=auth.uid() or public.is_admin_or_moderator()) with check (owner_id=auth.uid() or public.is_admin_or_moderator());
create policy events_delete_admin on public.events for delete using (public.is_admin());

create policy bookings_parties_read on public.bookings for select using (customer_id=auth.uid() or exists(select 1 from public.providers p where p.id=provider_id and p.owner_id=auth.uid()) or public.is_admin_or_moderator());
create policy bookings_customer_insert on public.bookings for insert with check (customer_id=auth.uid());
create policy bookings_parties_update on public.bookings for update using (customer_id=auth.uid() or exists(select 1 from public.providers p where p.id=provider_id and p.owner_id=auth.uid()) or public.is_admin_or_moderator()) with check (customer_id=auth.uid() or exists(select 1 from public.providers p where p.id=provider_id and p.owner_id=auth.uid()) or public.is_admin_or_moderator());
create policy bookings_admin_delete on public.bookings for delete using (public.is_admin());

create policy reviews_public_read on public.reviews for select using (status='published' or reviewer_id=auth.uid() or public.is_admin_or_moderator());
create policy reviews_own_insert on public.reviews for insert with check (reviewer_id=auth.uid());
create policy reviews_owner_admin_manage on public.reviews for update using (reviewer_id=auth.uid() or public.is_admin_or_moderator()) with check (reviewer_id=auth.uid() or public.is_admin_or_moderator());
create policy reviews_admin_delete on public.reviews for delete using (public.is_admin());

create policy messages_participants_read on public.messages for select using (sender_id=auth.uid() or receiver_id=auth.uid() or public.is_admin_or_moderator());
create policy messages_sender_insert on public.messages for insert with check (sender_id=auth.uid());
create policy messages_participants_update on public.messages for update using (sender_id=auth.uid() or receiver_id=auth.uid() or public.is_admin_or_moderator()) with check (sender_id=auth.uid() or receiver_id=auth.uid() or public.is_admin_or_moderator());
create policy messages_admin_delete on public.messages for delete using (public.is_admin());

create policy notifications_own_read on public.notifications for select using (user_id=auth.uid() or public.is_admin_or_moderator());
create policy notifications_own_update on public.notifications for update using (user_id=auth.uid() or public.is_admin_or_moderator()) with check (user_id=auth.uid() or public.is_admin_or_moderator());
create policy notifications_admin_insert on public.notifications for insert with check (public.is_admin_or_moderator() or user_id=auth.uid());
create policy notifications_admin_delete on public.notifications for delete using (public.is_admin_or_moderator());

create policy roles_own_read on public.user_roles for select using (user_id=auth.uid() or public.is_admin());
create policy roles_admin_manage on public.user_roles for all using (public.is_admin()) with check (public.is_admin());

create policy settings_public_read on public.site_settings for select using (true);
create policy settings_admin_manage on public.site_settings for all using (public.is_admin()) with check (public.is_admin());

create policy audit_admin_read on public.audit_log for select using (public.is_admin_or_moderator());
create policy audit_insert_authenticated on public.audit_log for insert with check (auth.uid()=actor_id);

-- Public storage bucket for approved provider media. Files are still protected for writes/deletes by storage RLS.
insert into storage.buckets (id,name,public) values ('provider-media','provider-media',true)
on conflict (id) do update set public=true;

drop policy if exists provider_media_public_read on storage.objects;
drop policy if exists provider_media_authenticated_upload on storage.objects;
drop policy if exists provider_media_owner_update on storage.objects;
drop policy if exists provider_media_owner_delete on storage.objects;
drop policy if exists provider_media_admin_delete on storage.objects;

create policy provider_media_public_read on storage.objects for select using (bucket_id='provider-media');
create policy provider_media_authenticated_upload on storage.objects for insert to authenticated
with check (bucket_id='provider-media' and (name like auth.uid()::text || '/%'));
create policy provider_media_owner_update on storage.objects for update to authenticated
using (bucket_id='provider-media' and owner_id=auth.uid()::text)
with check (bucket_id='provider-media' and owner_id=auth.uid()::text);
create policy provider_media_owner_delete on storage.objects for delete to authenticated
using (bucket_id='provider-media' and owner_id=auth.uid()::text);
create policy provider_media_admin_delete on storage.objects for delete to authenticated
using (bucket_id='provider-media' and public.is_admin_or_moderator());

-- Default settings.
insert into public.site_settings(key,value) values
('site_status','"Live"'::jsonb),
('provider_approval','"Manual approval"'::jsonb),
('featured_providers','[]'::jsonb)
on conflict (key) do nothing;

-- Admin setup: create the user in Authentication first, then run:
-- insert into public.user_roles(user_id,role) values ('AUTH-USER-UUID','admin') on conflict (user_id) do update set role='admin';
